### ISSUE TITLE
Починить Travis CI

### ISSUE THREAD

**Issue by azat-io** [azat-io/observer-bot#20]
При запуске тестов выдаётся ошибка `Cannot find module '../../etc/firebase-keys.json' from 'firebase.js'`. Нужно это дело пофиксить:
https://docs.travis-ci.com/user/encrypting-files/

**Comment by fletcherist** [comment]
Давай по этому сделаем просто замоканный firebase-keys.json 
и при инициализации будем писать красный консоль лог, что типа чувак, «сходи по ссылке и посмотри, как развернуть у себя».

Как идея?

**Comment by azat-io** [comment]
Да, давай. Почему бы и нет :+1:
